import { getCatalog } from '@/lib/repository';
import { filterSchools,compareSchools,checkSubjects } from '@/lib/logic';
import { z } from 'zod';
import { personalRequest } from '@/lib/personal-api';
import { searchNeisSchools } from '@/lib/neis';
export const dynamic='force-dynamic';
const querySchema=z.object({q:z.string().max(100).default(''),type:z.string().max(30).default('전체'),region:z.string().max(30).default('전체'),year:z.coerce.number().int().min(2025).max(2040).optional(),page:z.coerce.number().int().min(1).max(10000).default(1),limit:z.coerce.number().int().min(1).max(100).default(20),sort:z.enum(['name','date']).default('name')});
async function handle(req:Request,{params}:{params:Promise<{path:string[]}>}){try{const {path}=await params;const route=path.join('/');if(['me','profile','favorites','saved_events','notifications','account'].includes(path[0])||path[0]==='admin')return await personalRequest(req,path);const url=new URL(req.url);if(req.method==='GET'&&route==='schools/search'){const q=querySchema.parse(Object.fromEntries(url.searchParams));const data=await searchNeisSchools({q:q.q,region:q.region,page:q.page,limit:q.limit});return Response.json({...data,page:q.page,limit:q.limit});}const c=await getCatalog();if(req.method==='GET'){if(route==='catalog')return Response.json(c);const q=querySchema.parse(Object.fromEntries(url.searchParams));let result:unknown[]=[];if(route==='schools')result=filterSchools(c.schools,q.q,q.type,q.region,q.year??2027).sort((a,b)=>a.name.localeCompare(b.name,'ko'));else if(path[0]==='schools'&&path[1]){const d=c.schools.find(s=>s.id===path[1]);return d?Response.json(d):Response.json({error:'학교를 찾을 수 없습니다.'},{status:404})}else if(route==='compare')return Response.json(compareSchools(c.schools,(url.searchParams.get('ids')||'').split(',').filter(Boolean)));else if(route==='universities')result=c.departments.filter(d=>(!q.year||d.evidence.year===q.year)&&(d.university+d.name).includes(q.q)).sort((a,b)=>a.university.localeCompare(b.university,'ko'));else if(path[0]==='departments'&&path[1]){const d=c.departments.find(x=>x.id===path[1]);return d?Response.json(d):Response.json({error:'학과를 찾을 수 없습니다.'},{status:404})}else if(route==='events')result=c.events.filter(e=>!q.year||e.evidence.year===q.year).sort((a,b)=>a.date.localeCompare(b.date));else return Response.json({error:'요청 경로를 찾을 수 없습니다.'},{status:404});return Response.json({items:result.slice((q.page-1)*q.limit,q.page*q.limit),total:result.length,page:q.page,limit:q.limit});}if(req.method==='POST'&&route==='subject-check'){const body=z.object({departmentId:z.string().max(100),selected:z.array(z.string().max(100)).max(100),year:z.number().int(),curriculum:z.string().max(20)}).parse(await req.json());const d=c.departments.find(d=>d.id===body.departmentId);if(!d)return Response.json({error:'학과를 찾을 수 없습니다.'},{status:404});return Response.json({items:checkSubjects(d,body.selected,body.year,body.curriculum),isDemo:d.evidence.isDemo,information:d.requirements.length?'과목 조건 비교':'공식 정보 없음'});}return Response.json({error:'지원하지 않는 요청입니다.'},{status:405});}catch(e){return Response.json({error:e instanceof z.ZodError?'입력한 값을 확인해 주세요.':(e as Error).message},{status:400});}}
export {handle as GET,handle as POST,handle as PUT,handle as PATCH,handle as DELETE};
