'use client';
import { createContext, useContext, useEffect, useState, useCallback } from 'react';
import type { User } from '@supabase/supabase-js';
import type { School, Department, Event, Profile } from '@/types';
import { browserDB, demoMode } from '@/lib/supabase';
import { profileSchema } from '@/lib/schemas';
const defaultProfile:Profile={grade:'중3',region:'서울',highYear:2027,universityYear:2030,field:'전체'};
type Catalog={schools:School[];departments:Department[];events:Event[]};
type Note={id:string;title:string;read:boolean};
type State=Catalog&{profile:Profile;saveProfile:(p:Profile)=>Promise<void>;compare:string[];toggleCompare:(id:string)=>void;favorites:string[];savedEvents:string[];toggleSave:(kind:'favorites'|'saved_events',id:string)=>Promise<void>;user:User|null;demoAccount:boolean;startDemo:()=>void;logout:()=>Promise<void>;notice:string;notify:(s:string)=>void;loading:boolean;error:string;reload:()=>void;notes:Note[];readNote:(id:string)=>Promise<void>;authOpen:boolean;setAuthOpen:(b:boolean)=>void;isAdmin:boolean;clearLocal:()=>void;api:(path:string,init?:RequestInit)=>Promise<any>};
const Context=createContext<State|null>(null);
export function StateProvider({children}:{children:React.ReactNode}){
 const [catalog,setCatalog]=useState<Catalog>({schools:[],departments:[],events:[]}); const [loading,setLoading]=useState(true),[error,setError]=useState(''),[revision,setRevision]=useState(0);
 const [profile,setProfile]=useState(defaultProfile),[compare,setCompare]=useState<string[]>([]),[favorites,setFavorites]=useState<string[]>([]),[savedEvents,setSavedEvents]=useState<string[]>([]),[notes,setNotes]=useState<Note[]>([]),[user,setUser]=useState<User|null>(null),[demoAccount,setDemoAccount]=useState(false),[notice,notify]=useState(''),[authOpen,setAuthOpen]=useState(false),[isAdmin,setIsAdmin]=useState(false);
 const api=useCallback(async(path:string,init:RequestInit={})=>{ const session=await browserDB()?.auth.getSession(); const token=session?.data.session?.access_token; const r=await fetch(`/api/${path}`,{...init,headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`} :{}),...init.headers}}); const data=await r.json();if(!r.ok)throw new Error(data.error||'요청을 처리하지 못했습니다.');return data;},[]);
 useEffect(()=>{let active=true;setLoading(true);setError('');api('catalog').then(c=>active&&setCatalog(c)).catch(e=>active&&setError(e.message)).finally(()=>active&&setLoading(false));return()=>{active=false};},[api,revision]);
 useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem('compass.profile')||'null');const p=profileSchema.safeParse(saved);if(p.success)setProfile(p.data); const ids=JSON.parse(sessionStorage.getItem('compass.compare')||'[]'); if(Array.isArray(ids))setCompare(ids.filter(x=>typeof x==='string').slice(0,3));}catch{} const db=browserDB();if(!db)return;db.auth.getUser().then(({data})=>setUser(data.user));const {data}=db.auth.onAuthStateChange((_e,s)=>setUser(s?.user??null));return()=>data.subscription.unsubscribe();},[]);
 useEffect(()=>{if(!notice)return;const t=setTimeout(()=>notify(''),4500);return()=>clearTimeout(t)},[notice]);
 useEffect(()=>{if(!user){setIsAdmin(false);return;}let active=true;api('me').then(d=>{if(!active)return;setFavorites(d.favorites);setSavedEvents(d.savedEvents);setNotes(d.notes);setIsAdmin(d.isAdmin);const p=profileSchema.safeParse(d.profile);if(p.success)setProfile(p.data)}).catch(e=>notify(e.message));return()=>{active=false}},[user,api]);
 function startDemo(){if(!demoMode)return;setDemoAccount(true);setAuthOpen(false);try{const d=JSON.parse(sessionStorage.getItem('compass.demo')||'{}');setFavorites(Array.isArray(d.favorites)?d.favorites.filter((x:unknown)=>typeof x==='string'):[]);setSavedEvents(Array.isArray(d.savedEvents)?d.savedEvents.filter((x:unknown)=>typeof x==='string'):[]);}catch{}setNotes([{id:'demo-note',title:'예시 체험을 시작했어요. 저장 항목은 이 탭에서만 유지됩니다.',read:false}]);notify('계정 없이 이 탭에서 체험 중입니다.');}
 async function saveProfile(p:Profile){const parsed=profileSchema.parse(p);if(user)await api('profile',{method:'PUT',body:JSON.stringify(parsed)});setProfile(parsed);localStorage.setItem('compass.profile',JSON.stringify(parsed));notify('진학 설정을 저장했어요.');}
 function toggleCompare(id:string){setCompare(old=>{const school=catalog.schools.find(s=>s.id===id);const first=catalog.schools.find(s=>s.id===old[0]);if(old.includes(id)){const n=old.filter(x=>x!==id);sessionStorage.setItem('compass.compare',JSON.stringify(n));return n;}if(old.length>=3){notify('학교는 최대 3개까지 비교할 수 있어요.');return old;}if(first&&school&&first.evidence.year!==school.evidence.year){notify('같은 학년도의 학교를 선택하세요.');return old;}const n=[...old,id];sessionStorage.setItem('compass.compare',JSON.stringify(n));return n;});}
 async function toggleSave(kind:'favorites'|'saved_events',id:string){if(!user&&!demoAccount){setAuthOpen(true);return;} const old=kind==='favorites'?favorites:savedEvents;const next=old.includes(id)?old.filter(x=>x!==id):[...old,id];try{if(user)await api(kind,{method:old.includes(id)?'DELETE':'POST',body:JSON.stringify({id})});if(kind==='favorites')setFavorites(next);else setSavedEvents(next);if(demoAccount)sessionStorage.setItem('compass.demo',JSON.stringify({favorites:kind==='favorites'?next:favorites,savedEvents:kind==='saved_events'?next:savedEvents}));notify(old.includes(id)?'저장을 해제했어요.':'관심 목록에 저장했어요.');}catch(e){notify((e as Error).message)}}
 async function readNote(id:string){try{if(user)await api('notifications',{method:'PATCH',body:JSON.stringify({id})});setNotes(n=>n.map(x=>x.id===id?{...x,read:true}:x));}catch(e){notify((e as Error).message)}}
 function clearLocal(){localStorage.removeItem('compass.profile');sessionStorage.removeItem('compass.demo');sessionStorage.removeItem('compass.compare');setProfile(defaultProfile);setCompare([]);setFavorites([]);setSavedEvents([]);setNotes([]);setDemoAccount(false);}
 async function logout(){await browserDB()?.auth.signOut();setUser(null);setIsAdmin(false);clearLocal();notify('로그아웃했어요.');}
 return <Context.Provider value={{...catalog,profile,saveProfile,compare,toggleCompare,favorites,savedEvents,toggleSave,user,demoAccount,startDemo,logout,notice,notify,loading,error,reload:()=>setRevision(n=>n+1),notes,readNote,authOpen,setAuthOpen,isAdmin,clearLocal,api}}>{children}</Context.Provider>;
}
export function useApp(){const context=useContext(Context);if(!context)throw new Error('StateProvider is required');return context;}
