'use client';
import { Compass, House, School, GraduationCap, BookOpen, CalendarDays, Heart, Bell, Settings2, ChevronRight, ShieldCheck, Scale, LogIn, LogOut } from 'lucide-react';
import Link from 'next/link';
import { usePathname } from 'next/navigation';
import Dashboard from './dashboard';
import { StateProvider,useApp } from './app-state';
import { AuthDialog } from './auth-dialog';
import Views from './views';
import { demoMode } from '@/lib/supabase';
const nav=[['/','나의 대시보드',House],['/schools','고교 찾기',School],['/compare','학교 비교',Scale],['/universities','대학·학과 찾기',GraduationCap],['/planner','과목 플래너',BookOpen],['/calendar','입시 일정',CalendarDays],['/guides','입시 가이드',BookOpen]] as const;
export default function CompassApp(){return <Shell/>}
function Shell(){const path=usePathname(),s=useApp();const title=nav.find(n=>n[0]===path||n[0]!=='/'&&path.startsWith(n[0]))?.[1]||'입시 나침반';return <div className="shell"><a className="skip-link" href="#content">본문 바로가기</a><aside className="sidebar"><Link href="/" className="brand"><span className="brand-icon"><Compass size={27}/></span><span>입시 나침반<small>나에게 맞는 진학의 방향</small></span></Link><div className="workspace-label">MY COMPASS</div><nav aria-label="주 메뉴">{nav.map(([href,label,Icon])=><Link key={href} href={href} className={path===href?'active':''}><Icon size={19}/>{label}{path===href&&<ChevronRight size={16}/>}</Link>)}</nav><div className="nav-divider"/><nav aria-label="내 정보"><Link href="/saved"><Heart size={19}/>관심 목록</Link><Link href="/notifications"><Bell size={19}/>내 알림</Link><Link href="/settings"><Settings2 size={19}/>진학 설정</Link></nav><div className="sidebar-bottom"><ShieldCheck size={19}/><span>출처를 확인하는 습관<small>모든 선택의 시작입니다</small></span></div></aside><div className="main-wrap"><header className="topbar"><span>나의 진학 여정 <ChevronRight size={14}/> <b>{title}</b></span><div>{demoMode&&<span className="demo-dot">예시 데이터</span>}<Link className="icon-button" href="/saved" aria-label="관심 목록" title="관심 목록"><Heart size={19}/></Link><Link className="icon-button" href="/notifications" aria-label="알림" title="알림"><Bell size={20}/>{s.notes.some(n=>!n.read)&&<span className="notification-dot"/>}</Link>{s.user||s.demoAccount?<button onClick={s.logout} className="icon-button" title="로그아웃" aria-label="로그아웃"><LogOut size={19}/></button>:<button onClick={()=>s.setAuthOpen(true)} className="icon-button" title="로그인" aria-label="로그인"><LogIn size={19}/></button>}<Link className="avatar" href="/settings" aria-label="진학 설정">나</Link></div></header><main id="content">{s.loading?<div className="empty" aria-busy="true">진학 정보를 불러오는 중입니다.</div>:s.error?<div className="empty" role="alert"><h2>정보를 불러오지 못했어요</h2><p>{s.error}</p><button className="btn primary" onClick={s.reload}>다시 시도</button></div>:path==='/'?<Dashboard/>:<Views path={path}/>}<footer>입시 나침반 <span>학교와 대학의 최종 모집요강을 반드시 확인하세요.</span><Link href="/sources">출처 안내</Link><Link href="/privacy">개인정보처리방침</Link><Link href="/terms">이용약관</Link><Link href="/admin">자료 관리</Link></footer></main></div><AuthDialog/>{s.notice&&<div className="toast" role="status">{s.notice}</div>}</div>}
