import { createClient } from '@supabase/supabase-js';
import { z } from 'zod';
import { profileSchema,schoolSchema,departmentSchema,eventSchema } from './schemas';
export async function personalRequest(req:Request,path:string[]){const token=req.headers.get('authorization')?.match(/^Bearer (.+)$/)?.[1];if(!token)return Response.json({error:'로그인이 필요합니다.'},{status:401});const url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;if(!url||!key)return Response.json({error:'계정 연결을 준비 중입니다.'},{status:503});const db=createClient(url,key,{global:{headers:{Authorization:`Bearer ${token}`}},auth:{persistSession:false}});const {data:{user},error}=await db.auth.getUser(token);if(error||!user)return Response.json({error:'로그인을 다시 해 주세요.'},{status:401});const uid=user.id;const ok=(data:unknown)=>Response.json(data);const execute=async(query:PromiseLike<{data:any;error:any}>)=>{const r=await query;if(r.error)throw new Error('요청을 저장하지 못했습니다. 연결과 권한을 확인하세요.');return r.data};
if(path[0]==='admin'){const {data:admin}=await db.from('admin_users').select('user_id').eq('user_id',uid).maybeSingle();if(!admin)return Response.json({error:'관리자 권한이 필요합니다.'},{status:403});if(path[1]==='collect')return ok({message:'학교알리미 인증키와 항목별 이용 조건 검토가 필요하여 수집을 보류했습니다. 관리자 등록 출처만 수집할 수 있습니다.'});if(path[1]==='reviews'){if(req.method==='GET')return ok({items:await execute(db.from('review_items').select('*').order('created_at',{ascending:false}).limit(100))});if(req.method==='PATCH'){const body=z.object({id:z.uuid(),payload:z.record(z.string(),z.unknown())}).parse(await req.json());await execute(db.from('review_items').update({payload:body.payload}).eq('id',body.id).eq('status','pending'));return ok({saved:true})}if(req.method==='POST'){const {id}=z.object({id:z.uuid()}).parse(await req.json());const row=await execute(db.from('review_items').select('*').eq('id',id).single());const schema=row.kind==='school'?schoolSchema:row.kind==='department'?departmentSchema:eventSchema;const payload=schema.parse(row.payload);if(payload.evidence.isDemo||payload.evidence.status!=='reviewed'||!payload.evidence.sourceUrl||!payload.evidence.checkedAt)throw new Error('실제 공식 출처, 확인일, 검토 상태가 필요합니다.');await execute(db.rpc('approve_review',{review_id:id}));return ok({approved:true})}}return Response.json({error:'관리자 요청을 확인하세요.'},{status:404})}
if(path[0]==='me'&&req.method==='GET'){const profile=await execute(db.from('profiles').select('settings').eq('id',uid).maybeSingle());const favorites=await execute(db.from('favorites').select('entry_id').eq('user_id',uid));const saved=await execute(db.from('saved_events').select('entry_id').eq('user_id',uid));const notes=await execute(db.from('notifications').select('id,title,read').eq('user_id',uid).order('created_at',{ascending:false}));const admin=await execute(db.from('admin_users').select('user_id').eq('user_id',uid).maybeSingle());return ok({profile:profile?.settings,favorites:favorites.map((x:any)=>x.entry_id),savedEvents:saved.map((x:any)=>x.entry_id),notes,isAdmin:!!admin})}
if(path[0]==='profile'&&req.method==='PUT'){const settings=profileSchema.parse(await req.json());await execute(db.from('profiles').upsert({id:uid,settings}));return ok({saved:true})}
if(['favorites','saved_events'].includes(path[0])){const table=path[0];if(req.method==='GET')return ok(await execute(db.from(table).select('*').eq('user_id',uid)));const {id}=z.object({id:z.string().min(1).max(100)}).parse(await req.json());if(req.method==='POST'){await execute(db.from(table).upsert({user_id:uid,entry_id:id}));return ok({saved:true})}if(req.method==='DELETE'){await execute(db.from(table).delete().eq('user_id',uid).eq('entry_id',id));return ok({deleted:true})}}
if(path[0]==='notifications'){if(req.method==='GET')return ok(await execute(db.from('notifications').select('id,title,read').eq('user_id',uid)));if(req.method==='PATCH'){const {id}=z.object({id:z.uuid()}).parse(await req.json());await execute(db.from('notifications').update({read:true}).eq('user_id',uid).eq('id',id));return ok({saved:true})}}
if(path[0]==='account'&&req.method==='DELETE'){const secret=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!secret)return Response.json({error:'계정 삭제 연결을 준비 중입니다. 운영자에게 문의해 주세요.'},{status:503});const admin=createClient(url,secret,{auth:{persistSession:false}});const {error}=await admin.auth.admin.deleteUser(uid);if(error)throw new Error('계정을 삭제하지 못했습니다. 다시 시도해 주세요.');return ok({deleted:true})}
return Response.json({error:'지원하지 않는 요청입니다.'},{status:405});}
